version: 2
jobs:
  checkout_code:
    working_directory: ~/anotherfizz
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  build_image:
    working_directory: ~/anotherfizz
    docker:
      - image: circleci/python:3.6.1
    steps:
      - attach_workspace:
          at: .
      - run: |
          sudo docker build -t sayfizz2-latest .
          sudo docker login -u popsoften -p $DOKCER_PASS
          sudo docker tag sayfizz2-latest popsoften/sayfizz2:latest
          sudo docker push popsoften/sayfizz2:latest


  unit_tests:
    working_directory: ~/anotherfizz
    docker:
      - image: circleci/python:3.6.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unittest
          command: python fizzbuzztest.py

workflows:
  version: 2
  say-fizz-pipeline:
    jobs:
      - checkout_code
      - unit_tests:
          requires:
            - checkout_code
      - build_image:
          requires:
            - unit_tests